# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeTpB5DqRDEupidm3JWRzQKTtm4ZXA_R
"""

import random
minimo = 1
maximo  = 100
numero_secreto = random.randint(minimo,maximo)
tentativas = 0
while True:
  tentativas += 1
  palpite = int(input(f"digite um numero entre {minimo} e {maximo}: "))
  if palpite == numero_secreto:
    print(f"parabens! voce adivinho em {tentativas} tentativas!")
    break
  elif palpite > numero_secreto:
    print(f"o numero secreto é MENOR que {palpite}.")
  else:
    print(f"o numero secreto é MAIOR que {palpite}.")